"""Manajemen cron jobs: metadata di DB, apply ke /etc/cron.d/weborn.

Di mode local/wsl config ditulis ke /etc/cron.d agar langsung aktif;
di mode dry-run cukup ditulis ke CONFIG_DIR untuk ditinjau.
"""
import re

from ..config import CONFIG_DIR
from ..executors import get_executor

SCHEDULE_RE = re.compile(r"^(\S+ ){4}\S+$")
ALIASES = ("@reboot", "@daily", "@hourly", "@weekly", "@monthly", "@yearly")


def valid_schedule(schedule: str) -> bool:
    s = schedule.strip()
    return SCHEDULE_RE.match(s) is not None or s in ALIASES


class CronManager:
    def __init__(self, executor=None):
        self.executor = executor or get_executor()

    def build_file(self, crons: list[dict]) -> str:
        lines = ["# Generated by Weborn - jangan edit manual", ""]
        for c in crons:
            if not c["enabled"]:
                continue
            # Sanitize: reject commands containing newlines (injection prevention)
            cmd = c["command"].replace("\n", "").replace("\r", "")
            schedule = c["schedule"].replace("\n", "").replace("\r", "")
            user = c["user"].replace("\n", "").replace("\r", "")
            lines.append(f"{schedule} {user} {cmd}")
        return "\n".join(lines) + "\n"

    async def apply(self, crons: list[dict]):
        content = self.build_file(crons)
        conf = CONFIG_DIR / "cron.d"
        conf.mkdir(parents=True, exist_ok=True)
        (conf / "weborn.conf").write_text(content, encoding="utf-8")
        if self.executor.mode not in ("local", "wsl"):
            return
        ok = await self.executor.run(
            "bash", "-c", "test -d /etc/cron.d && echo yes || echo no")
        if "yes" not in ok.stdout:
            return
        await self.executor.write_file("/etc/cron.d/weborn", content)
        await self.executor.run(
            "bash", "-c",
            "pkill -HUP cron 2>/dev/null || service cron reload 2>/dev/null || true")
